name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: set up signing
      run: |
        echo "$SIGNING_KEYSTORE" | base64 -d > ~/keystore
        mkdir -p ~/.gradle/
        echo "signingStoreLocation=/home/runner/keystore" > ~/.gradle/gradle.properties
        echo "signingStorePassword=password" >> ~/.gradle/gradle.properties
        echo "signingKeyAlias=alias" >> ~/.gradle/gradle.properties
        echo "signingKeyPassword=password" >> ~/.gradle/gradle.properties
      env:
        SIGNING_KEYSTORE: ${{ secrets.KEYSTORE }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: app/build/outputs/apk/release
